name: Build All

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Build All'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
      - run: echo ""
