name: Build Conda package manual

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Build conda package'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ubuntu-latest
        python-version: [3.6, 3.7, 3.8]
        ginjinn-distribution: [ginjinn-gpu-pt15_cu101_linux]
    name: Python ${{ matrix.python-version }} example
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge, pytorch
      - run: conda --version
      - run: which python
      - name: Install dependencies
        run: |
          conda install pytest conda-build anaconda-client pip
      - name: Build and publish GinJinn
        run: |
          conda config --set anaconda_upload yes
          conda-build conda.recipe/${{ matrix.ginjinn-distribution }} --token ${{ secrets.ANACONDA_TOKEN }} --user AGOberprieler --label nightly
      - name: Test with pytest
        run: |
          python -m pytest