# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Conda package

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Build conda package'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Install Miniconda
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-py37_4.8.2-MacOSX-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        hash -r
        rm miniconda.sh
        conda config --set auto_update_conda false
    - name: Install dependencies
      run: |
        conda install Python=${{ matrix.python-version }} pytest conda-build anaconda-client
    - name: Test with pytest
      run: |
        pytest
