package:
  name: ginjinn-gpu_development
#  version: {{ GIT_DESCRIBE_TAG }}_pt15_cu101
  version: test_pt15_cu101

source:
#   git_rev:
  git_url: https://github.com/AGOberprieler/GinJinn_development

requirements:
  build:
    - python {{ python }}
    - setuptools
    - pytorch==1.5.0
    - torchvision==0.6.0
    - cudatoolkit=10.1
    - pip

  run:
    - python {{ python }}
    - pytorch==1.5.0
    - torchvision==0.6.0
    - cudatoolkit=10.1
    - opencv
    - scikit-image
    - pandas
    - pycocotools
    - mock
    - imantics
    - segmentation-refinement

build:
  skip: true # [not linux]
entry_points:
   - ginjinn = ginjinn.commandline.main:main

# test:
#   imports:
#     -

about:
  home: https://github.com/AGOberprieler/GinJinn_development
  license: MIT
  summary: Object detection pipeline for the extraction of structures from digitized herbarium specimens
